name: Join Paths Example

on:
  push:
    branches:
      - main

jobs:
  join-paths:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Join Paths
      id: join_paths
      shell: pwsh
      run: |
        $basePath = "C:\path\to"
        $fullPath = join-path $basePath 'Common7\IDE\CommonExtensions\Microsoft\TestWindow'
        echo "action_state=$fullPath" >> $GITHUB_ENV

    - name: Display Full Path
      run: |
        Write-Output "Full Path: $env.action_state"
